services:
  clase10-proyecto-devops:
    image: localhost:8082/clase10-proyecto-devops
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /tmp/ficheros-contenedor:/var/ficheros
    environment:
      - AMBIENTE=development
      - API_KEY=/run/secrets/api-key
    secrets:
      - api-key
secrets:
   api-key:
     file: api-key.txt
