services:
  clase10-proyecto-devops:
    image: localhost:8082/clase10-proyecto-devops
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - /tmp/ficheros-contenedor:/var/ficheros
