services:
  clase10-proyecto-devops:
    image: localhost:8082/clase10-proyecto-devops
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AMBIENTE=development
      - API_KEY=112233445566778899
    volumes:
      - /tmp/ficheros-contenedor:/var/ficheros
